version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    volumes:
      - backend_data:/app/data
      - uploads_data:/app/public/joinus_uploads
    ports:
      - "127.0.0.1:1037:1037"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "127.0.0.1:8081:80"

volumes:
  backend_data:
  uploads_data:
